missing tabs

diff --git a/src/Makefile.qt.include b/src/Makefile.qt.include
--- a/src/Makefile.qt.include
+++ b/src/Makefile.qt.include
@@ -306,24 +306,24 @@ QT_QM=$(QT_TS:.ts=.qm)
 .SECONDARY: $(QT_QM)
 
 qt/bitcoinstrings.cpp: $(libppcoin_server_a_SOURCES) $(libppcoin_common_a_SOURCES) $(libppcoin_cli_a_SOURCES)
-    @test -n $(XGETTEXT) || echo "xgettext is required for updating translations"
-    @cd $(top_srcdir); XGETTEXT=$(XGETTEXT) share/qt/extract_strings_qt.py
+	@test -n $(XGETTEXT) || echo "xgettext is required for updating translations"
+	@cd $(top_srcdir); XGETTEXT=$(XGETTEXT) share/qt/extract_strings_qt.py
 
 translate: qt/bitcoinstrings.cpp $(QT_FORMS_UI) $(QT_FORMS_UI) $(PPCOIN_QT_CPP) $(PPCOIN_QT_H) $(PPCOIN_MM)
-    @test -n $(LUPDATE) || echo "lupdate is required for updating translations"
-    @QT_SELECT=$(QT_SELECT) $(LUPDATE) $^ -locations relative -no-obsolete -ts qt/locale/bitcoin_en.ts
+	@test -n $(LUPDATE) || echo "lupdate is required for updating translations"
+	@QT_SELECT=$(QT_SELECT) $(LUPDATE) $^ -locations relative -no-obsolete -ts qt/locale/bitcoin_en.ts
 
 $(QT_QRC_CPP): $(QT_QRC) $(QT_QM) $(QT_FORMS_H) $(RES_ICONS) $(RES_IMAGES) $(RES_MOVIES) 
-    @cd $(abs_srcdir); test -f $(RCC) && $(RCC) -name bitcoin -o $(abs_builddir)/$@ $< || \
-      echo error: could not build $@
-    $(SED) -i.bak -e '/^\*\*.*Created:/d' $@ && rm $@.bak
-    $(SED) -i.bak -e '/^\*\*.*by:/d' $@ && rm $@.bak
+	@cd $(abs_srcdir); test -f $(RCC) && $(RCC) -name bitcoin -o $(abs_builddir)/$@ $< || \
+	  echo error: could not build $@
+	$(SED) -i.bak -e '/^\*\*.*Created:/d' $@ && rm $@.bak
+	$(SED) -i.bak -e '/^\*\*.*by:/d' $@ && rm $@.bak
 
 CLEAN_QT = $(nodist_qt_libppcoinqt_a_SOURCES) $(QT_QM) $(QT_FORMS_H) qt/*.gcda qt/*.gcno
 
 CLEANFILES += $(CLEAN_QT)
 
 peercoin_qt_clean: FORCE
-    rm -f $(CLEAN_QT) $(qt_libppcoinqt_a_OBJECTS) $(qt_ppcoin_qt_OBJECTS) qt/ppcoin-qt$(EXEEXT) $(LIBPPCOINQT)
+	rm -f $(CLEAN_QT) $(qt_libppcoinqt_a_OBJECTS) $(qt_ppcoin_qt_OBJECTS) qt/ppcoin-qt$(EXEEXT) $(LIBPPCOINQT)
 
 peercoin_qt : qt/peercoin-qt$(EXEEXT)
